services:
  psp:
    image: psp
    build:
      context: .
      dockerfile: PSP/Dockerfile
      target: development
    ports:
      - "8080:80"
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=pspsecret
    depends_on:
      - database
  
  database:
    image: 'postgres:latest'
    ports:
      - "5432"
    environment:
      POSTGRES_PASSWORD: pspsecret
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
